"""Feature router registry.

Add new route modules here, then include their ``router`` in ``ROUTERS``.
The order mirrors the old monolithic ``app/main.py`` registration order so
path matching behavior remains stable.
"""

from . import (
    accountability_pairs,
    admin_applications,
    admin_audit_logs,
    admin_challenges,
    admin_community,
    admin_content,
    admin_dashboard,
    admin_feature_flags,
    admin_faqs,
    admin_homepage,
    admin_masterclasses,
    admin_me,
    admin_notifications,
    admin_revenue,
    admin_subscribers,
    admin_subscription_plans,
    admin_support,
    admin_trials,
    admin_uploads,
    admin_user_management,
    admin_users,
    admin_workouts,
    ai_coach_victor,
    ai_meal_analysis,
    ai_nutrition,
    ai_workout_plan,
    analytics_events,
    applications,
    auth,
    challenges,
    community,
    completion_cards,
    content,
    invites,
    jobs,
    journal,
    longevity_os,
    me,
    me_notifications,
    payments,
    payment_events,
    points_log,
    subscription_plans,
    support,
    system,
    trial,
    uploads,
    websockets,
    workout_logs,
    workouts,
)

_ROUTER_MODULES = (
    analytics_events,
    workout_logs,
    completion_cards,
    invites,
    payment_events,
    payments,
    points_log,
    accountability_pairs,
    system,
    workouts,
    ai_workout_plan,
    auth,
    me,
    me_notifications,
    jobs,
    admin_me,
    longevity_os,
    content,
    admin_content,
    admin_feature_flags,
    admin_faqs,
    admin_notifications,
    admin_revenue,
    admin_subscription_plans,
    subscription_plans,
    admin_masterclasses,
    admin_subscribers,
    applications,
    support,
    admin_applications,
    admin_support,
    community,
    admin_community,
    challenges,
    websockets,
    admin_challenges,
    admin_dashboard,
    admin_users,
    admin_user_management,
    trial,
    admin_trials,
    admin_workouts,
    admin_uploads,
    uploads,
    journal,
    ai_meal_analysis,
    ai_coach_victor,
    ai_nutrition,
    admin_audit_logs,
    admin_homepage,
)

ROUTERS = tuple(module.router for module in _ROUTER_MODULES)
ROUTER_MODULES = tuple(module.__name__ for module in _ROUTER_MODULES)

__all__ = ["ROUTERS", "ROUTER_MODULES"]
