services:
  api:
    build: .
    container_name: victory-backend-api
    env_file:
      - .env
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
